const Axios = require(`axios`);
const fs = require('fs');
const path = require('path')
let config;

const gadwickEndpoint = "https://3i07lk1jl8.execute-api.us-east-1.amazonaws.com";

async function updateStubs()
{
    try
    {
        fs.existsSync(path)
    }
    catch (e)
    {
        console.log(`Gadwick has not been configured, run 'gadwick configure' first.`);
        return;
    }
    const config = JSON.parse(fs.readFileSync('gadwick-config.json', 'utf8'));
    console.log(`Finding features from Gadwick...`)
    if (!config.client_secret)
    {
        console.log(`No client secret found for app. Run 'gadwick config'.`);
        return;
    }
    const testSuiteDirectoryPath = config.test_directory;
    const response = await Axios.get(`${gadwickEndpoint}/features/s/${config.client_secret}`)
    const features = response.data;
    if (features.length === undefined || features.length === null)
    {
        console.log(`Failed to get features from Gadwick.`);
        return;
    }
    // console.dir(response.data.data);
    // console.log(`Found ${features.length} features:\n${features.map((feature) => feature.feature_name).join("\n")}`)
    // TODO: Resolve file name conflicts between local & gadwick
    fs.readdir(testSuiteDirectoryPath, function (err, files) {
        //handling error
        if (err) {
            return console.log('Unable to scan directory: ' + err);
        } 
        //listing all files using forEach
        const testFiles = []
        files.forEach(function (file) {
            if (fs.statSync(path.join(testSuiteDirectoryPath, file)).isFile()) {
                if (file.endsWith('.spec.js')) {
                    // Do whatever you want to do with the file
                    // console.log(file); 
                    testFiles.push(file.replace('.spec.js', ''));
                }
            }
        });
        let idMap = [];
        for (const gadwickFeature of features)
        {
            if (testFiles.includes(gadwickFeature.name))
            {
                console.log(`[OLD]\t${gadwickFeature.name}`);
            }
            else
            {
                console.log(`[NEW]\t${gadwickFeature.name}`);
                const fileData =
                [
                    `/** Test block generated by Gadwick */`,
                    `describe(\`${gadwickFeature.name}\`, function() {`,
                    `\tit(\`${gadwickFeature.description}\`, function() {`,
                    gadwickFeature.steps.map((step) => `\t\t// ${step}`),
                    `\t})`,
                    `})`
                ]
                idMap.push({ id: gadwickFeature.id, name: gadwickFeature.name });
                fs.writeFile(path.join(testSuiteDirectoryPath, `${gadwickFeature.name.replaceAll(" ", "_")}.spec.js`), fileData.join("\n"), (err) => {
                    if (err) throw err;
                    console.log(`New stub test file created for ${gadwickFeature.name}`);
                });
            }
        }
        const map = config.idMap;
        for (const id of idMap)
        {
            map.ids[id.id] = id.name;
            map.names[id.name] = id.id;
        }
        const newConfig = JSON.stringify({ ...config, idMap: map }, null, 2);
        fs.writeFile(`gadwick-config.json`, newConfig, (err) => {
            if (err) throw err;
            console.log(`Updated config with mapping:`);
            console.log(newConfig);
        });
        const gadwickNames = features.map((f) => f.feature_name);
        for (const localFeature of testFiles)
        {
            if (!gadwickNames.includes(localFeature))
            {
                console.log(`[LOCAL]\t${localFeature}`);
            }
        }
    });
}

module.exports = { updateStubs }