const { exec } = require("child_process");

async function cmd(script)
{
    return new Promise((resolve, reject) => exec(script, (e, out, err) =>
    {
        if (e) { reject(e); }
        else if(err) { reject(err); }
        else { resolve(out); }
    }));
}

/** Test block generated by Gadwick */
describe(`NPM Module`, function() {
	it(`Can update based on config`, async function() {
        // await cmd(`mkdir temp`)
        const output = await cmd(`node gadwick.js update`)
        // TODO: Test the output makes sense
        // TODO: Check the files exist
        // console.log(output)
        await cmd(`rm temp/*.spec.js`)
        // await cmd(`rmdir temp`)
	})
})